[Variables]
IconSize=Large
MiniIconSize=16
MiniIconSpace=28

Item1Name=%USERNAME%
Item1Icon=#fa-user#
Item1Folder=%USERPROFILE%

Item2Name=Documents
Item2Icon=#fa-file-text#
Item2Folder=[ShellPersonal]

Item3Name=Pictures
Item3Icon=#fa-image#
Item3Folder=[ShellMyPictures]

Item4Name=Music
Item4Icon=#fa-music#
Item4Folder=[ShellMyMusic]

Item5Name=Videos
Item5Icon=#fa-film#
Item5Folder=[ShellMyVideo]

Item6Name=Downloads
Item6Icon=#fa-download#
Item6Folder=%USERPROFILE%\Downloads

Item7Name=Start Menu
Item7Icon=#fa-windows#
Item7Folder=[ShellPrograms]

Item8Name=Desktop
Item8Icon=#fa-desktop#
Item8Folder=[ShellDesktop]

Item9Name=Favorite
Item9Icon=#fa-star#
Item9Folder=[ShellFavorites]

Item10Name=Libraries
Item10Icon=#fa-folder#
Item10Folder=%USERPROFILE%\AppData\Roaming\Microsoft\Windows\Libraries