[Variables]
; Locale settings
; Languages: en, ru
Lang=en

; Widget colors in RGB format (not RGBA or hex)
DefaultColor=255,255,255
ClockColor=#DefaultColor#
DateColor=#DefaultColor#
PlayerColor=#DefaultColor#
NoteColor=#DefaultColor#
LauncherColor=#DefaultColor#

; Custom note colors
ImportantNoteColor=255,128,128
QuestionableNoteColor=255,255,128
DoneNoteColor=128,255,128

; Maximum widget sizes
ClockWMax=320
ClockHMax=130
DateWMax=320
DateHMax=130
PlayerWMax=580
PlayerHMax=160
NoteWMax=450
NoteHMax=150
LauncherWMax=345
LauncherHMax=360

; Widget corners
; Valid options:
; -- "default"
; -- "square"
; -- "triangle"
DefaultCorners=square
ClockCorners=default
DateCorners=default
PlayerCorners=square
NoteCorners=default
LauncherCorners=default

; Widget corner positions
; Valid options:
; -- "top_left"
; -- "top_right"
; -- "bottom_left"
; -- "bottom_right"
DefaultPosition=top_left
ClockPosition=top_left
DatePosition=bottom_left
PlayerPosition=top_right
NotePosition=top_right
LauncherPosition=top_left

; Minified widgets
ClockMini=1
DateMini=1
PlayerMini=1
NoteMini=1
LauncherMini=1

; Date and time formats
TimeFormat="%H:%M:%S"
TimeFormatMini="%H:%M:%S"
DateFormat="%d.%m.%Y"
DateFormatMini="%d.%m.%Y"

; Note widget settings
NoteRefreshTime=5
NoteNoTitlePlaceholder=~~~

; Player widget settings
PlayerName=AIMP

; Opacity settings
OpacityMain=255
OpacityButton=128
OpacityInactive=48
OpacityBG=32

