[Variables]

;Clock
ClockTranslate = "Monday":"Monday", "Tuesday":"Tuesday", "Wednesday":"Wednesday", "Thursday":"Thursday", "Friday":"Friday", "Saturday":"Saturday", "Sunday":"Sunday", "January":"January", "February":"February", "March":"March", "April":"April", "May":"May", "June":"June", "July":"July", "August":"August", "September":"September", "October":"October", "November":"November", "December":"December"

;Weather
Language = "en"
LanguageSite = "en-EN"
WeatherTranslate = "Now": "Now", "Today":"Today", "Tonight":"Tonight", "Tomorrow":"Tomorrow", "like":"like", "Monday":"Monday", "Tuesday":"Tuesday", "Wednesday":"Wednesday", "Thursday":"Thursday", "Friday":"Friday", "Saturday":"Saturday", "Sunday":"Sunday"

;Calendar
Mon = Mon
Tue = Tue
Wed = Wed
Thu = Thu
Fri = Fri
Sat = Sat
Sun = Sun
January = January
February = February
March = March
April = April
May = May
June = June
July = July
August = August
September = September
October = October
November = November
December = December

;Info
InfoTranslate = "cores":"cores"